DROP DATABASE IF EXISTS badmovies;

CREATE DATABASE badmovies;

USE badmovies;

DROP TABLE IF EXISTS favorites;

CREATE TABLE favorites (
    id INTEGER AUTO_INCREMENT,
    movieId INTEGER NULL DEFAULT NULL UNIQUE,
    movieTitle MEDIUMTEXT NULL DEFAULT NULL,
    releaseDate MEDIUMTEXT NULL DEFAULT NULL,
    voteAverage INTEGER NULL DEFAULT NULL,
    imageLink MEDIUMTEXT NULL DEFAULT NULL,
    PRIMARY KEY (id)
);